version: '3.8'

services:
    web:
        build: .
        env_file:
            -   .env
        ports:
            - "3000:3000"
        volumes:
            - .:/go/usr/src/app
        command: go run cmd/main.go -b 0.0.0.0
    db:
        image: postgres:alpine
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - postgres-db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    postgres-db: